Numerador = int(input('Digite um numero para ver sua tabuada: '))
print('-' * 15)
print('{} x {:2} = {} '.format(Numerador, 1, Numerador * 1))
print('{} x {:2} = {} '.format(Numerador, 2, Numerador * 2))
print('{} x {:2} = {} '.format(Numerador, 3, Numerador * 3))
print('{} x {:2} = {} '.format(Numerador, 4, Numerador * 4))
print('{} x {:2} = {} '.format(Numerador, 5, Numerador * 5))
print('{} x {:2} = {} '.format(Numerador, 6, Numerador * 6))
print('{} x {:2} = {} '.format(Numerador, 7, Numerador * 7))
print('{} x {:2} = {} '.format(Numerador, 8, Numerador * 8))
print('{} x {:2} = {} '.format(Numerador, 9, Numerador * 9))
print('{} x {:2} = {} '.format(Numerador, 10, Numerador * 10))
print('-' * 15)

